# Generated by Django 6.0.1 on 2026-01-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='Title',
        ),
    ]
